services:

  db:
    image: postgres:15
    container_name: docker_practise_db
    # ❌ OLD (xavfli: DB internetga ochiq)
    # ports:
    #   - "5432:5432"

    env_file:
      - ".env"
    volumes:
      - docker_practise_data:/var/lib/postgresql/data
    networks:
      - global_network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker_practise_web

    # ❌ OLD (xavfli: backend internetga ochiq)
    # ports:
    #   - "8000:8000"

    ## ✅ NEW (faqat nginx kira oladi) <- nginx alohida docker compose da bolsa
    #expose:
    #  - "8000"

    # server nginx uchun
    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - .:/app
    
    depends_on:
      - db
    env_file:
      - ".env"
    networks:
      - global_network

networks:
  global_network:
    name: global_network
    external: true

volumes:
  docker_practise_data: